#ifndef LIBUNITTESTS_GLOBAL_H
#define LIBUNITTESTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBUNITTESTS_LIBRARY)
#  define LIBUNITTESTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBUNITTESTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBUNITTESTS_GLOBAL_H
